# Generated by Django 4.0.4 on 2022-05-31 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetchFromApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='currency',
            new_name='currencies',
        ),
    ]
